export enum ErrorCode {
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  REQUEST_TIMEOUT = 408,
  PRECONDITION_FAILED = 412,
  UNPROCESSABLE_ENTITY = 422,
  FAILED_DEPENDENCY = 424,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
  CONNECTION_TIMED_OUT = 522,
}

export enum ValidationMessages {
  required = 'Please enter this value',
  email = 'Invalid email id',
  mobile = 'Invalid mobile no',
  integer = 'Please enter a valid intege value',
  regex = 'Please enter a valid value',
  inverseRegex = 'Please enter a valid value',
  maxValue = 'Value exceeds the maximum value allowed.',
  minValue = 'Value is less than the minimum value allowed.',
  maxLength = 'Character limit exceeded.',
  minLength = 'Not enough characters entered.',
  range = 'Value is not in the given range.',
  pan = 'Expected format AAAAA5555A',
  aadhar = 'Expected format 555555555555',
  gstin = 'Expected format 22AAAAA0000A1Z5',
  pincode = 'Please enter a valid 6 digit PIN code',
  alphaNumeric = 'Please enter only alphabets and numbers.',
  alphaNumericWithSpace = 'Invalid Characters.',
  multipleOf = 'Please enter the value which is multiple of a desired number.',
}